spelling_correct = {' responding Union Township': {' responding in Township'},
 '2 Lebanon Township': {'2Lebanon Township'},
 '49 Rescue, Raritan Township': {'For an unrescued resident in Township'},
 'Alexander Township': {'I was here in Township'},
 'Alexandria': {'Alexanrian'},
 'Alexandria Township': {'Alexander Township', 'out of the injury township'},
 'Amwell': {'AML', 'Amarillo', 'Amel', 'Anwaul', 'Danwell', 'Emmel', 'End West',
            'Enwood', 'Hamel', 'Hamil', 'Humboldt', 'Humbolt', 'Sandwell',
            'Seminole', 'Stanwell'},
 'Amwell Township': {'Ammo', 'Ammo Township', 'Amo Township', 'Animal Township',
                     'Antelope Township', 'San Juan Township',
                     'St. Louis Township'},
 'Barley Sheaf': {'Barley Sheep', 'Barley Chief'},
 'Bethlehem': {'Baltham', 'Tebethelehem', 'SLAM'},
 'Bethlehem Township': {'Bethlehem Tech', 'Bethlehem Town',
                        'Breslaham Township', 'Buffam Township',
                        'back from Township'},
 'Bloomsbury': {'Bluesberry'},
 'Boonton': {'Boond', 'Boondon'},
 'Branchburg': {'Bransford'},
 'Bucks County': {'Fox County'},
 'CO2 alarm': {'seal alarm'},
 'Califon Borough': {'Califontine Borough', 'Californ Borough',
                     'California Borough', 'Caliphon Borough'},
 'Clinton': {'Caldwin', 'Clindon', 'Flint', 'Quentin', 'Clemson', 'Clifdon'},
 'Clinton Township': {'Clamp Township', 'Clayton Township', 'Clem Township',
                      'Client Township', 'Climb Township', 'Clint Township',
                      'Clinton Tachib', 'Hunt Township'},
 'Croton': {'Croaten'},
 'Delaware Township': {'Dillard Township'},
 'East Amwell': {'East Amok', 'East Anvil', 'East Danville', 'East Demo',
                 'East Elmwood', 'East Emerald', 'East Envil', 'East Enwil',
                 'East Enwold', 'East Island', 'East Monclair',
                 'East Montclair', 'East Samoa', 'East Samuel'},
 'East Amwell Township': {'East 1 Township', 'East End 1 Township',
                          'East Inland Township', 'East No. 1 Township',
                          'East and 1 Township', 'Estanbul Township',
                          'east ammo township', 'eastbound township'},
 'Fire, Clinton Township': {'Firecliff Township'},
 'Fire, Holland Township': {'Firehall and Township'},
 'Fire, Raritan Township': {'Fireware and Townshipib', 'Firebird and Township'},
 'Flemington': {'Bloomington Borough', 'Clemington', 'Flamingo Borough',
                'Flamington', 'Flem', 'Fulmington', 'Plumb', 'Plumbington',
                'Plummedon', 'Wilmington'},
 'Flemington Borough': {'Farm Borough', 'Feminine Borough', 'Flam Borough',
                        'Helm Borough', 'Hunt Borough', 'Lam Borough',
                        'Leam Borough'},
 'Franklin Township': {'Gateway Township'},
 'Frenchtown': {'French Town'},
 'Gardner': {'Garner'},
 'Glen Gardener': {'Longardner'},
 'Glen Gardner': {'Glen Garner', 'Glengardner', 'Glenn Gardener', 'Gwanganur',
                  'Gwangarne'},
 'Glen Gardner Borough': {'Eglint Gardner Borough', 'Glen Gardener Borough',
                          'Glenbrenner Borough', 'Glenn Gardner Borough',
                          'Glenn-Gardner Borough', 'Spongly Gardner Borough',
                          'to Gardner Borough'},
 'Greyrock': {'Gray Rock'},
 'Hampton Borough': {'Hamp Borough'},
 'High Bridge': {'Highbridge', 'highbridge'},
 'High Bridge Borough': {'Harbridge Boroug', 'Hybridsboro'},
 'Holland': {'Fireholland'},
 'Holland Township': {'Hall and Township', 'Hall in Townshi',
                      'hall and township'},
 'Hunterdon': {'Huntingdon', 'Hunterdondang', 'Hunter', 'Hunterdondon'},
 'Hunterdon Care Center': {'Hunter Care Center', 'Hunter and Care Center',
                           'Hunterdon and Care Center'},
 'Hunterdon County': {'Hundred and County', 'Hunt Count'},
 'Kingwood Township': {'Kingway Township', 'Kenwood Township', 'with Township'},
 'Lambertville': {'City Of Lamberthal', 'City Of Lambertville', 'Lamarville',
                  'Lambauville', 'Lambeau', 'Lambeauville', 'Lamberfell',
                  'Lamberlost City', 'Lamberphil', 'Lamberthal', 'Lamberthill',
                  'Lamberthville', 'Lambertville City', 'Lambertvilleville',
                  'Lamberville', 'Lambeville', 'Lamborough', 'Lamerill',
                  'Lamertville', 'Lamerville', 'Land Revolt', 'Landryville',
                  'Landville', 'Laneville', 'Lanternville', 'Lantville',
                  'Laramieville', 'Laramville', 'Laraville', 'Larrinville',
                  'Limberville', 'Limerick', 'Lumberphil',
                  'city of Lambertville', 'city of lamberthal'},
 'Lambertville City': {'Lambert City'},
 'Lebannon': {'Levidon'},
 'Lebannon Township': {'11th and Township', 'Leavitt and Township'},
 'Lebanon Borough': {'Leavenham Borough', 'Leavenworth Borough'},
 'Lebanon Township': {'11 Township', '11 in Township', '11 on Township',
                      '11 to Township', '111 on Township', 'LeBlanc Township',
                      'Leavenant Township', 'Leavett on Township',
                      'Leavitt Township', 'Leavittown Township',
                      'Lebannon Township', 'Limited Township', 'Loden Township',
                      'Lubbenon Township', 'limited township'},
 'Lopatcong': {'Wapakong', 'Lopatkin'},
 'Oldwick': {'Old Wick'},
 'Paging': {'Puging'},
 'Pittstown': {'Pitstown', 'Pitts Town', 'Pitsdown'},
 'Raritan': {'Rareton', 'Renton', 'Brainerd'},
 'Raritan Township': {'1-Rayerson Township', 'Aaron Township',
                      'Active Township', 'American Township',
                      'Araratou Township', 'Arlington Township',
                      'Arrington Township', 'Arroyo Township',
                      'Awareness Township', 'Barr Township', 'Barret Township',
                      'Barrett Township', 'Barrett and Township',
                      'Barrington Township', 'Bear and Township',
                      'Bear in township', 'Brereton Township', 'Burn Township',
                      'Burr Township', 'Burrington Township', 'Byrne Township',
                      'Emergency Township', 'Emergent Township',
                      'Enran Township', 'Enrandon Township',
                      'Environment Township', 'Erickson Township',
                      'Ericsson Township', 'Err Township', 'Fire and Township',
                      'Frerich Township', 'Harrison Township',
                      'Jamaica Township', 'Larrick Township',
                      'Mareden Township', 'Maren Township', 'Marin Township',
                      'Marion Township', 'Marriott Township',
                      'Marriott and Township', 'Mary township', 'Mer Township',
                      'Merrit Township', 'Merritt Township', 'Oregon Township',
                      'Origin Township', 'RT in Township', 'Ranger Township',
                      'Rare Earth Township', 'Rare Township',
                      'Rare in Township', 'Rarit Township', 'Raritan Towns',
                      'Rarity Township', 'Rear End Township',
                      'Rear Entrant and Township', 'Rear Township',
                      'Rear and Township', 'Rear end township',
                      'Rear in Township', 'Rectum Township', 'Reder Township',
                      'Redwood Township', 'Ree Township', 'Regent Township',
                      'Rehabilitation Township', 'Ren Township',
                      'Renn Township', 'Renn Townshipip', 'Rent Township',
                      'Renter and Township', 'Renwick Township',
                      'Responder to Township', 'Responding to Township',
                      'Riordan Township', 'Road and Township', 'Round Township',
                      'Routed Township', 'Rur Township', 'Ryder Township',
                      'Ryer Township', 'Ryerson Township', 'Varon Township',
                      'Varr Township', 'Veri Township', 'Verican Township',
                      'Vernon Township', 'Verrant Township',
                      'Verrant and Townshipip', 'Verridon Township',
                      'Wanderers and Township', 'Warr Township',
                      'Warrant and Township', 'Wind River Township',
                      'a rare detachment', 'and Emergency Township',
                      'at Township', 'direct from Township',
                      'emergency township', 'emergent township',
                      'errant township', 'fire in township',
                      'for your township', 'in a random township',
                      'in the township', 'rare and township',
                      'rare in Township', 'rare in a township', 'rare in town',
                      'rare in township', 'rare township', 'rarity township',
                      'ready to Township', 'ready to township',
                      'rear and township', 'rear end Township',
                      'rear end of Township', 'rear end tangent',
                      'rear end township', 'rear to Township', 'rear township',
                      'rear-end in township', 'rear-end township',
                      'rescue in township', 'respond to Township',
                      'responder at your township', 'responder in township',
                      'responder out to Township', 'responding to township',
                      'right after the township', 'right around Township',
                      'right in Township', 'right in township',
                      'right into Township', 'right of township',
                      'right on township', 'right on your township',
                      'right to Township', 'road and township',
                      'route and attach', 'route and township',
                      'route attached', 'route in Township',
                      'router to Township', 'routing township',
                      'running to the township', 'running to township',
                      'someRaritan Townshiphip', 'variant in township',
                      'variant township', "we're at the Township",
                      "we're at your township", "we're here in Township",
                      "we're in Township", "we're in township",
                      "we're on Township", "we're out in Township",
                      'where at the township', 'where to Township',
                      'where to township?', 'writing to Township'},
 'Readington': {'Reddington', 'Ridington', 'Redd'},
 'Readington Township': {'Burl Township', 'Read Town', 'Read Township',
                         'Reed Township', 'ready for Township',
                         'ready for township', 'responding to Township',
                         'riding to Township', 'right on Township',
                         'routing to Township', 'running from Township',
                         'running to Township', 'writing in Township'},
 'Repeating': {'Reading ', 'Greetings', 'Skiing'},
 'Responding': {'Spawning'},
 'Route 78': {'route 70'},
 'Shop Rite': {'shop right'},
 'Stanton': {'Standon'},
 'Tewksbury': {'Tewsbury', 'Chiefsbury', 'Eastbury', 'Keeksbury'},
 'Tewksbury Township': {'123 Township', '23 Township', '3 Township',
                        '6th grade Township', 'Antiques Ferry Township',
                        'Dukes Ferry Township', 'Seas Ferry Township',
                        'Sioux Ferry Township', 'Tewkesbury Township',
                        'Tisray Township', 'Tixbury Township',
                        'Tuxbury Township', 'Two Ferry Township',
                        'X-ray Township', 'to Express Township',
                        'to Ferry Township', 'to express township',
                        'two ferry township', 'two-ferry township',
                        'two-story township'},
 'Town of Clinton': {'town of Clinton', 'Santa Clinton'},
 'Township': {'Tach', 'Tadge', 'Tash', 'Tatchett', 'Townshipship',
              'Townshipshipline'},
 'Union Township': {'Deunion Township', 'Unit Township', 'Indian Township'},
 'Walter Foran': {'Walter Farran'},
 'Washington Borough': {'Wash Borough'},
 'Washington Township': {'Wash Township'},
 'West Amwell': {'West Elmwood', 'West Emerald', 'West Hamilton', 'West Hamlet',
                 'West Hamlin', 'West Samuel', 'West Township'},
 'West Amwell Township': {'West 91st Township', 'West Amount Township',
                          'West Anmol Township', 'West Bama Townshipib',
                          'West Danville Township', 'with Amwell Township'},
 'Wharton': {'Whardon'},
 'Whippany': {'Whibbany'},
 'chest pain': {'Chesepeake', 'Chesapine'},
 'described': {'ascribed'},
 'fall victim': {'full victim'},
 'fire alarm activation': {'firearm activation'},
 'into Bucks County': {'Indoplex County'},
 'into Frenchtown Borough': {'InterFrenchtown Borough'},
 'leg pain': {'Lake Payne'},
 'lift assist': {'Leipzig', 'left assist'},
 'male party': {'mail party', 'Mail party'},
 'psych eval': {'psyche vial'},
 're-alert': {'Real Alert'},
 'responding': {'spawning'},
 'responding Union Township': {'responding in township'},
 'syncopal': {'Singapore', 'sickable', 'singapore', 'sinkable', 'syncable',
              'thinkable'},
 'syncopal episode': {'sinkhole episode', 'single episode'},
 'syncope': {'synchro'},
 'vomiting': {'abominate'}}
