spelling_correct = {'Alexandria Township': ['Alexander Township'],
 'Amwell': ['AML', 'Enwood', 'Danwell', 'End West', 'Amel', 'Seminole',
            'Sandwell', 'Humbolt', 'Stanwell', 'Amarillo'],
 'Amwell Township': ['Ammo', 'Amo Township', 'Animal Township',
                     'Antelope Township', 'Ammo Township'],
 'Barley Sheaf': ['Barley Sheep', 'Barley Chief'],
 'Bethlehem': ['SLAM', 'Baltham', 'Tebethelehem'],
 'Bethlehem Township': ['Bethlehem Tech', 'Breslaham Township',
                        'Bethlehem Town', 'Buffam Township'],
 'Bloomsbury': ['Bluesberry'],
 'Boonton': ['Boond', 'Boondon'],
 'Branchburg': ['Bransford'],
 'CO2 alarm': ['seal alarm'],
 'Califon Borough': ['California Borough', 'Californ Borough',
                     'Califontine Borough', 'Caliphon Borough'],
 'Clinton': ['Quentin', 'Caldwin', 'Clindon', 'Clemson', 'Flint', 'Clifdon'],
 'Clinton Township': ['Clint Township', 'Clayton Township', 'Clinton Tachib',
                      'Client Township', 'Clem Township', 'Clamp Township',
                      'Climb Township'],
 'Croton': ['Croaten'],
 'East Amwell': ['East Amok', 'East Anvil', 'East Danville', 'East Demo',
                 'East Elmwood', 'East Emerald', 'East Envil', 'East Enwold',
                 'East Enwil', 'East Island', 'East Monclair', 'East Montclair',
                 'East Samoa', 'East Samuel'],
 'East Amwell Township': ['East 1 Township'],
 'Flemington': ['Flamington', 'Clemington', 'Plumbington', 'Wilmington',
                'Bloomington Borough', 'Flem', 'Flamingo Borough', 'Fulmington',
                'Plummedon', 'Plumb'],
 'Frenchtown': ['French Town'],
 'Gardner': ['Garner'],
 'Glen Gardener': ['Longardner'],
 'Glen Gardner': ['Glenn Gardener', 'Glen Garner', 'Glengardner'],
 'Greyrock': ['Gray Rock'],
 'High Bridge': ['Highbridge', 'highbridge'],
 'High Bridge Borough': ['Hybridsboro'],
 'Holland': ['Fireholland'],
 'Hunterdon': ['Huntingdon', 'Hunter', 'Hunterdondon', 'Hunterdondang'],
 'Hunterdon Care Center': ['Hunter and Care Center',
                           'Hunterdon and Care Center', 'Hunter Care Center'],
 'Hunterdon County': ['Hunt Count'],
 'Kingwood Township': ['with Township', 'Kenwood Township'],
 'Lambertville': ['Lambeville', 'Lamerill', 'Lamberville', 'Lamerville',
                  'Laramville', 'Limberville', 'Lamarville', 'Lambauville',
                  'Lumberphil', 'Lamberthill', 'Lamberthville', 'Laramieville',
                  'Lambeau', 'Lambeauville', 'Lamberphil', 'Lamberthal',
                  'Land Revolt', 'Landville', 'Lamberthal', 'Lamberfell',
                  'Lambertvilleville', 'Lamborough', 'Landryville', 'Laneville',
                  'Lanternville', 'Lantville', 'Laraville', 'Larrinville',
                  'Laneville', 'Limerick'],
 'Lambertville City': ['Lambert City'],
 'Lebannon': ['Levidon'],
 'Lebanon Township': ['11 on Township', '111 on Township', '11 to Township',
                      'Leavett on Township', '11 Township'],
 'Lopatcong': ['Lopatkin', 'Wapakong'],
 'Oldwick': ['Old Wick'],
 'Paging': ['Puging'],
 'Pittstown': ['Pitsdown', 'Pitstown', 'Pitts Town'],
 'Raritan': ['Rareton', 'Renton', 'Brainerd'],
 'Raritan Township': ['where to Township', "we're in Township",
                      'route in Township', 'Aaron Township',
                      'Arrington Township', 'Barrington Township',
                      'Burrington Township', 'Barret Township',
                      'Brereton Township', 'Rarity Township', 'Rarit Township',
                      'rear end tangent', 'ready to Township',
                      'ready to township', 'rare in a township', 'rare in town',
                      'rare in township', 'route and attach', 'route attached',
                      'Barrett Township', 'American Township',
                      'Arlington Township', 'Arroyo Township',
                      'Awareness Township', 'Burn Township', 'Byrne Township',
                      'Rarit Township', 'Ericsson Township',
                      'Verridon Township', 'at Township', 'Marriott Township',
                      'Rare Township', 'Rarity Township'],
 'Readington': ['Reddington', 'Ridington', 'Redd'],
 'Readington Township': ['responding to Township', 'running to Township',
                         'routing to Township', 'riding to Township',
                         'right on Township', 'Read Township', 'Reed Township',
                         'Read Town'],
 'Repeating': ['Skiing', 'Reading ', 'Greetings'],
 'Responding': ['Spawning'],
 'Route 78': ['route 70'],
 'Shop Rite': ['shop right'],
 'Stanton': ['Standon'],
 'Tewksbury': ['Tewsbury', 'Chiefsbury'],
 'Tewksbury Township': ['123 Township'],
 'Town of Clinton': ['town of Clinton', 'Santa Clinton'],
 'Township': ['Tach', 'Tash', 'Tadge', 'Tatchett'],
 'Union Township': ['Unit Township'],
 'Walter Foran': ['Walter Farran'],
 'Washington Borough': ['Wash Borough'],
 'Washington Township': ['Wash Township'],
 'West Amwell': ['West Elmwood', 'West Emerald', 'West Hamilton', 'West Hamlet',
                 'West Hamlin'],
 'Wharton': ['Whardon'],
 'Whippany': ['Whibbany'],
 'chest pain': ['Chesepeake', 'Chesapine'],
 'described': ['ascribed'],
 'fall victim': ['full victim'],
 'fire alarm activation': ['firearm activation'],
 'leg pain': ['Lake Payne'],
 'lift assist': ['left assist', 'Leipzig'],
 'responding': ['spawning'],
 'syncopal': ['sinkable', 'sickable', 'singapore', 'Singapore', 'syncable',
              'thinkable'],
 'syncopal episode': ['single episode', 'sinkhole episode'],
 'syncope': ['synchro'],
 'vomiting': ['abominate']}
