config = {
    "database": "sqlite:///pywx.db",
    "airportdb": "airports.dat",
    "forecast_io_secret": "0171c33dabdcd6e3fe4f01ccf62ad1b",
    "max_msg_length": "375",
    "host": "irc.server.org",
    "port": 6667,
    "nick": "wx",
    "ident": "wx",
    "realname": "wx",
    "pass": "",
    "chans": ["#weather"],
    "admins": ["~ident@hostname"],
    "ownermask": "~ident@hostname",
    "quitmsg": "peace out",
    "redlink_user": '',
    "redlink_pass": '',
    "youtube_key": "",
    "imgur_id": "",
    "imgur_secret": "",
}
